name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set RUST_BACKTRACE
      run: |
           echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
           echo "OPENSSL_NO_PKG_CONFIG=true" >> $GITHUB_ENV
           echo "PKG_CONFIG_x86_64-unknown-linux-gnu=/usr/bin/pkg-config" >> $GITHUB_ENV
           echo "PKG_CONFIG_x86_64_unknown_linux_gnu=/usr/bin/pkg-config" >> $GITHUB_ENV
           echo "HOST_PKG_CONFIG=/usr/bin/pkg-config" >> $GITHUB_ENV
           echo "PKG_CONFIG=/usr/bin/pkg-config" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
